name: E2E Tests with Playwright

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
        # Add emojis to make the matrix more fun
        emoji: [🦄, 🚀, ⚡️, 🎯]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        flutter pub get
        npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Build Flutter Web
      run: flutter build web
    
    - name: Start Flutter Web Server
      run: |
        flutter run -d web-server --web-port 3000 &
        sleep 30
    
    - name: Run Playwright tests
      run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      env:
        CI: true
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.shardIndex }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30

  test-results:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all test results
      uses: actions/download-artifact@v4
      with:
        path: playwright-report/
        pattern: playwright-report-*
        merge-multiple: true
    
    - name: Upload test results to GitHub
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  test-results-on-failure:
    needs: test
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all test results
      uses: actions/download-artifact@v4
      with:
        path: playwright-report/
        pattern: playwright-report-*
        merge-multiple: true
    
    - name: Upload test results to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-failure
        path: playwright-report/
        retention-days: 30 